/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_BinaryOperations */

#ifndef _Included_utils_BinaryOperations
#define _Included_utils_BinaryOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_BinaryOperations
 * Method:    getPercentage
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_getPercentage
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     utils_BinaryOperations
 * Method:    setPercentage
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_setPercentage
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     utils_BinaryOperations
 * Method:    initialize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_initialize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     utils_BinaryOperations
 * Method:    aquote
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_aquote
  (JNIEnv *, jobject, jlong);

/*
 * Class:     utils_BinaryOperations
 * Method:    setId
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_setId
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     utils_BinaryOperations
 * Method:    cross
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_cross
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     utils_BinaryOperations
 * Method:    mutation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_utils_BinaryOperations_mutation
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
